### ISSUE TITLE
Go command in Makefile moved

### ISSUE THREAD

**Issue by elowing** [justincampbell/homebrew-formulae#1]
==> make install PREFIX=/usr/local/Cellar/tmux-pomodoro/1.1.1

go get -t
go get code.google.com/p/go.tools/cmd/cover
the code.google.com/p/go.tools/cmd/cover command has moved; use golang.org/x/tools/cmd/cover instead.

**Comment by mattamizer** [comment]
FWIW This is still an issue, not sure why it was closed.
