### ISSUE TITLE
tmux-pomodoro: Cover moved to golang.org

### ISSUE THREAD

**Issue by mattamizer** [justincampbell/homebrew-formulae#2]
When trying to install via `brew install tmux-pomodoro` the makefile throws the following error:

```
==> Installing justincampbell/formulae/tmux-pomodoro
==> Downloading https://github.com/justincampbell/tmux-pomodoro/archive/v1.1.1.tar.gz
==> Downloading from https://codeload.github.com/justincampbell/tmux-pomodoro/tar.gz/v1.1.1
######################################################################## 100.0%
==> mkdir /usr/local/Cellar/tmux-pomodoro/1.1.1/bin
==> make install PREFIX=/usr/local/Cellar/tmux-pomodoro/1.1.1
go get -t
go get code.google.com/p/go.tools/cmd/cover
warning: code.google.com is shutting down; import path code.google.com/p/go.tools/cmd/cover will stop working
the code.google.com/p/go.tools/cmd/cover command has moved; use golang.org/x/tools/cmd/cover instead.
make: *** [dependencies] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/justincampbell/homebrew-formulae/issues
```

**Comment by elowing** [comment]
@mattamizer and i realized the tmux-pomodoro formula doesn't find the correct version on the repo. what takes precedence: homepage, url, sha1, or head?

matt got it to work by adding --HEAD to the install, but then it fails for me on the gometalinter. since i don't have go installed, there's no valid GOPATH. is that an intentional dependency?

**Comment by justincampbell** [comment]
Would be ok without gometalinter for homebrew. Could move its `go get`/`install` to the `linter` Make target.

**Comment by justincampbell** [comment]
@elowing @mattamizer I think this was actually solved a while ago in the source, but I never released/updated the Homebrew formula :x 

Let me know if it's still broken after a `brew update`. Thanks!
